/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sequence;

/**
 *
 * @author josue
 */
public class Reportes extends javax.swing.JFrame {

    public Reportes() {
        initComponents();
        setUserInfo();
        
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Elementos/GameIcon.png")).getImage());
    }

    private void setUserInfo(){
        String BattleLog = "";
        int Battle = 1; 
        for (int i = Main_Sequence.gestorUsuarios.getUserLog().getHistorial().size() - 1; i >= 0 ; i --){
            BattleLog += Battle + ". " + Main_Sequence.gestorUsuarios.getUserLog().getHistorial().get(i) + "\n";
            Battle++;
        }
        
        Historial.setText(BattleLog);
        PlayerPoints.setText("Puntos de " + Main_Sequence.gestorUsuarios.getUserLog().getUsername() + ": " + Main_Sequence.gestorUsuarios.getUserLog().getPoints());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historial = new javax.swing.JTextArea();
        PlayerPoints = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sequence");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 120, 40));

        Historial.setEditable(false);
        Historial.setColumns(20);
        Historial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Historial.setLineWrap(true);
        Historial.setRows(5);
        Historial.setWrapStyleWord(true);
        Historial.setFocusable(false);
        jScrollPane1.setViewportView(Historial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 270));

        PlayerPoints.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PlayerPoints.setText("Puntos: ");
        jPanel1.add(PlayerPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 540, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Historial;
    private javax.swing.JLabel PlayerPoints;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
